-- 코드를 입력하세요
# SELECT A.CAR_ID
# FROM CAR_RENTAL_COMPANY_CAR AS A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
# ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = '세단' AND 
# START_DATE LIKE '2022-10%'
# ORDER BY CAR_ID DESC

SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR  
WHERE CAR_TYPE = '세단' AND
CAR_ID IN (SELECT CAR_ID 
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
         WHERE START_DATE LIKE '2022-10%')
ORDER BY CAR_ID DESC