-- 코드를 입력하세요
SELECT R1.PRODUCT_CODE, sum(R1.PRICE * R2.SALES_AMOUNT) AS SALES
from PRODUCT R1
join OFFLINE_SALE R2
on R1.PRODUCT_ID = R2.PRODUCT_ID
group by r1.PRODUCT_CODE
order by SALES desc, PRODUCT_CODE;