SELECT R1.ITEM_ID, R1.ITEM_NAME, R1.RARITY
FROM ITEM_INFO  AS R1
JOIN ITEM_TREE  AS R2
  ON R1.ITEM_ID = R2.ITEM_ID
WHERE NOT EXISTS (
  SELECT 1
  FROM ITEM_TREE AS R3
  WHERE R3.PARENT_ITEM_ID = R2.ITEM_ID   -- t.ITEM_ID를 부모로 두는 자식이 없으면 leaf
)
ORDER BY R1.ITEM_ID DESC;